import type { Card } from '../schema'

/**
 * 2-point FCI cards. Proofread from the Czech translation of the FCI Rally Obedience
 * rules, valid from 1 Feb 2025, §5 (`sourcePage` = page of that PDF).
 */
export const FCI_TWO_POINT_CARDS: Card[] = [
  {
    code: '201',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: '2x čelem vzad, pes za psovodem',
    nameEn: '2 x TURN AROUND DOG BEHIND',
    description: [
      'Psovod provede obrat do té strany, na které se nachází pes, zatímco pes provádí obrat na tu stranu, kde se nachází psovod. Pes obchází psovoda zezadu a vrací se na výchozí stranu u nohy psovoda a společně pokračují v opačném směru. Po 1 - 2 m provede psovod znovu obrat do té strany, na které se nachází pes, zatímco pes znovu provádí obrat na tu stranu, kde se nachází psovod. Pes opět obchází psovoda zezadu, vrací se na výchozí stranu u nohy psovoda a společně pokračují ve stejném (původním) směru, jako před zahájením cviku.',
    ],
    sequencing: {},
    image: '201',
    sourcePage: 22,
  },
  {
    code: '202',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Dvojitý obrat o 180°, první vpravo, druhý vlevo',
    nameEn: 'DOUBLE 180° TURN, RIGHT THEN LEFT',
    description: [
      'Tým společně provede těsný obrat o 180° doprava a pokračuje opačným směrem. Po 1 -2 m tým společně provede těsný obrat o 180° doleva a pokračuje dál původním směrem jako před zahájením cviku.',
    ],
    sequencing: {},
    image: '202',
    sourcePage: 22,
  },
  {
    code: '203',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Dvojitý obrat o 180°, první vlevo, druhý vpravo',
    nameEn: 'DOUBLE 180° TURN, LEFT THEN RIGHT',
    description: [
      'Tým společně provede těsný obrat o 180° doleva a pokračuje opačným směrem. Po 1 – 2 m tým společně provede těsný obrat o 180° doprava a pokračuje dál původním směrem jako před zahájením cviku.',
    ],
    sequencing: {},
    image: '203',
    sourcePage: 22,
  },
  {
    code: '204',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Stop, lehni, sedni',
    nameEn: 'STOP, DOWN, SIT',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Psovod velí psa do pozice lehni, následně zpět do pozice sedni. Pes zůstává v pozici sedni, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '204',
    sourcePage: 22,
  },
  {
    code: '205',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Stop, stůj',
    nameEn: 'STOP, STAND',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Psovod velí psa do pozice stůj. Pes zůstává v pozici stůj, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '205',
    sourcePage: 22,
  },
  {
    code: '206',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Stop, stůj, sedni',
    nameEn: 'STOP, STAND, SIT',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Psovod velí psa do pozice stůj, následně zpět do pozice sedni. Pes zůstává v pozici sedni, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '206',
    sourcePage: 22,
  },
  {
    code: '207',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Stop, stůj, lehni',
    nameEn: 'STOP, STAND, DOWN',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Psovod velí psa do pozice stůj, následně zpět do pozice lehni. Pes zůstává v pozici lehni, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '207',
    sourcePage: 23,
  },
  {
    code: '208',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Stop, stůj, okolo psa',
    nameEn: 'STOP, STAND, WALK AROUND',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Psovod velí psa do pozice stůj. Zatímco pes zůstává stát, psovod jej obchází zepředu a vrací se do výchozí pozice po boku psa. Pes zůstává stát, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '208',
    sourcePage: 23,
  },
  {
    code: '209',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Stop, předsednutí, přiřazení zprava doleva, stop',
    nameEn: 'STOP, CALL FRONT STOP, RIGHT TO LEFT, STOP',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Následně je pes velen do předsednutí před psovodem. Poté psovod velí psovi povel k přiřazení, které pes vykonává tak, že míjí psovoda zepředu po jeho pravé straně a zezadu jej obchází zpět k levé noze, kde zaujímá pozici sedni. Pes zůstává sedět, dokud tým nepokračuje vpřed. Návrat k vedení po levé straně.',
    ],
    sequencing: {
      // p. 23: "Návrat k vedení po levé straně."
      endSide: 'left',
    },
    image: '209',
    sourcePage: 23,
  },
  {
    code: '210',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Stop, předsednutí, přiřazení přímo doleva',
    nameEn: 'STOP, CALL FRONT STOP, LEFT TO LEFT, STOP',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Následně je pes velen do předsednutí před psovodem. Poté psovod velí psovi povel k přiřazení. Pes vykonává přiřazení přímo k levé noze psovoda, kde zaujímá pozici sedni. Pes zůstává sedět, dokud tým nepokračuje vpřed. Návrat k vedení po levé straně.',
    ],
    sequencing: {
      // p. 23: "Návrat k vedení po levé straně."
      endSide: 'left',
    },
    image: '210',
    sourcePage: 23,
  },
  {
    code: '211',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Stop, 1 krok vpřed, 90° vpravo v bok, 1 krok, přivolání, stop',
    nameEn: 'STOP, 1 STEP FORWARD, 90° RIGHT TURN 1 STEP, CALL, STOP',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Pes zůstává sedět, zatímco psovod provede 1 krok vpřed, zastaví se, následně provede obrat vpravo v bok o 90° a udělá opět 1 krok vpřed v novém směru a zastaví se. Krok doprava může být proveden buď rovnou nebo se psovod otočí na místě a poté provede 1 krok. Následně psovod přivolává psa, který usedá u stejné nohy psovoda jako na začátku cviku (žádná změna strany vedení). Pes zůstává sedět, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '211',
    sourcePage: 23,
  },
  {
    code: '212',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Stop, 1 krok vpřed, 90° vlevo v bok, 1 krok, přivolání, stop',
    nameEn: 'STOP, 1 STEP FORWARD, 90° LEFT TURN 1 STEP, CALL, STOP',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Pes zůstává sedět, zatímco psovod provede 1 krok vpřed, zastaví se, následně provede obrat vlevo v bok o 90° a udělá opět 1 krok vpřed v novém směru a zastaví se. Krok doleva může být proveden buď rovnou nebo se psovod otočí na místě a poté provede 1 krok. Následně psovod přivolává psa, který usedá u stejné nohy psovoda jako na začátku cviku (žádná změna strany vedení). Pes zůstává sedět, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '212',
    sourcePage: 23,
  },
  {
    code: '213',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Stop, 180° vpravo, vpřed',
    nameEn: 'STOP, 180° RIGHT TURN, FORWARD',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Tým provede na místě společně těsný obrat o 180° doprava a pokračuje vpřed v opačném směru.',
    ],
    sequencing: {},
    image: '213',
    sourcePage: 24,
  },
  {
    code: '214',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Stop, 180° vlevo, vpřed',
    nameEn: 'STOP, 180° LEFT TURN, FORWARD',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Tým provede na místě společně těsný obrat o 180° doleva a pokračuje vpřed v opačném směru.',
    ],
    sequencing: {},
    image: '214',
    sourcePage: 24,
  },
  {
    code: '215',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Stop, 180° vpravo, stop',
    nameEn: 'STOP, 180° RIGHT TURN, STOP',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Tým provede na místě společně těsný obrat o 180° doprava, zastaví se a pes je velen do pozice sedni. Pes zůstává sedět, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '215',
    sourcePage: 24,
  },
  {
    code: '216',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Stop, 180° vlevo, stop',
    nameEn: 'STOP, 180° LEFT TURN, STOP',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Tým provede na místě společně těsný obrat o 180° doleva, zastaví se a pes je velen do pozice sedni. Pes zůstává sedět, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '216',
    sourcePage: 24,
  },
  {
    code: '217',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Stop, 90° vpravo, 1 krok, stop',
    nameEn: 'STOP, 90° RIGHT TURN 1 STEP, STOP',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Psovod provede obrat vpravo o 90°, udělá 1 krok vpřed a zastaví se. Krok může být proveden buď přímo, nebo psovod nejprve provede obrat na místě a poté udělá jeden krok. Pes se pohybuje společně s psovodem a současně se zastavením se psovoda znovu zaujímá pozici sed. Pes zůstává sedět, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '217',
    sourcePage: 24,
  },
  {
    code: '218',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Stop, 90° vlevo, 1 krok, stop',
    nameEn: 'STOP, 90° LEFT TURN 1 STEP, STOP',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Psovod provede obrat vlevo o 90°, udělá 1 krok vpřed a zastaví se. Krok může být proveden buď přímo, nebo psovod nejprve provede obrat na místě a poté udělá jeden krok. Pes se pohybuje společně s psovodem a současně se zastavením se psovoda znovu zaujímá pozici sed. Pes zůstává sedět, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '218',
    sourcePage: 24,
  },
  {
    code: '219',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Stop, 1 krok, stůj, 2 kroky, sedni, 3 kroky, lehni',
    nameEn: 'STOP, 1 STEP STAND, 2 STEPS STOP, 3 STEPS DOWN',
    description: [
      'Psovod se zastaví a pes si sedá u nohy psovoda. Následně psovod udělá 1 krok vpřed a zastaví se. Pes se pohybuje současně s psovodem a po zastavení psovoda je velen do pozice stůj. Psovod následně udělá dva kroky vpřed a zastaví se. Pes se pohybuje současně s psovodem a po zastavení psovoda je pes velen do pozice sedni. Následně provede psovod tři kroky vpřed a zastaví se. Pes se pohybuje současně s psovodem a po jeho zastavení je velen do pozice lehni. Pes zůstává ležet, dokud tým nepokračuje vpřed.',
    ],
    sequencing: {},
    image: '219',
    sourcePage: 24,
  },
  {
    code: '220',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'A',
    points: 2,
    name: 'Otočka',
    nameEn: 'SPIN',
    description: [
      'Zatímco se tým pohybuje vpřed, pes provede v přímém směru kruhovou otočku ve směru od psovoda.',
    ],
    sequencing: {},
    image: '220',
    sourcePage: 25,
  },
  {
    code: '221',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'B',
    points: 2,
    name: 'Rušivé vlivy',
    nameEn: 'DISTRACTIONS',
    description: [
      'Dva kužely jsou umístěny 2,5 - 3 m od sebe. Vzdálenost dalších dvou rušivých prvků je 1,5 - 2 m od sebe. Tým vstupuje do figury tak, jak určí rozhodčí a kolem kuželů provede kompletní figuru 8, přičemž spojnici mezi rušivými prvky překročí celkem 3x. Jako rušivé prvky mohou být použity hračky, pamlsky nebo obojí.',
    ],
    sequencing: {
      equipment: ['cones', 'bowls'],
    },
    image: '221',
    sourcePage: 25,
  },
  {
    code: '222',
    ruleset: 'FCI',
    kind: 'exercise',
    placement: 'D',
    points: 2,
    name: 'Vyslání přes překážku',
    nameEn: 'SEND OVER JUMP',
    description: [
      'Dva metry před překážkou se nachází karta. Ne dříve než na její úrovni, vysílá psovod psa k překonání překážky a sám pokračuje vpřed podél překážky. Psovod může zrychlit tempo, aby stihl dohnat psa za překážkou',
    ],
    sequencing: {
      equipment: ['jump'],
    },
    image: '222',
    sourcePage: 25,
  },
]
