import type { Card } from '../schema'

/**
 * Proofread from Zkušební řád Rally Obedience v ČR 2026, příloha 1 (`sourcePage` = page
 * of the regulation). Sequencing rules cite the regulation; see plan §5.
 */
export const RO_Z_CARDS: Card[] = [
  {
    code: 'Z-001',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop',
    description: [
      'Tým se zastaví u karty v místě pro provedení cviku a zaujme základní pozici. (pes si může sednout sám či na povel)',
    ],
    subParts: [
      { text: 'sedni', main: true },
      { text: 'psovod stojí vedle psa', main: false },
    ],
    sequencing: {},
    image: 'z-001',
    sourcePage: 19,
  },
  {
    code: 'Z-002',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop – lehni',
    description: [
      'Tým se zastaví u karty v místě pro vykonání cviku a zaujme základní pozici. Na povel psovoda si pes lehá.',
    ],
    subParts: [
      { text: 'Sedni', main: false },
      { text: 'lehni', main: true },
      { text: 'po zaujetí každé pozice psovod stojí vedle psa', main: false },
    ],
    sequencing: {},
    image: 'z-002',
    sourcePage: 19,
  },
  {
    code: 'Z-003',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop – lehni – sedni',
    description: [
      'Tým zastaví u karty v místě pro vykonání cviku a zaujme základní pozici. Na povel psovoda si pes lehá. Na další povel psovoda si pes sedá.',
    ],
    subParts: [
      { text: 'sedni', main: false },
      { text: 'lehni', main: false },
      { text: 'sedni', main: false },
      { text: 'po zaujetí každé pozice psovod stojí vedle psa', main: false },
    ],
    sequencing: {},
    image: 'z-003',
    sourcePage: 19,
  },
  {
    code: 'Z-004',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop – okolo psa',
    description: [
      'Tým zastaví u karty v místě pro vykonání cviku a zaujme základní pozici. Psovod může dát povel k setrvání na místě a obejde sedícího psa zepředu a zastaví se opět v základní pozici, kde krátce setrvá. Pes přitom nesmí změnit polohu ani pozici.',
    ],
    subParts: [
      { text: 'sedni', main: true },
      { text: 'psovod okolo psa, pes zůstává sedět', main: true },
      { text: 'psovod stojí po ukončení vedle psa', main: false },
    ],
    sequencing: {},
    image: 'z-004',
    sourcePage: 20,
  },
  {
    code: 'Z-005',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop – lehni – okolo psa',
    description: [
      'Tým zastaví u karty v místě pro vykonání cviku a zaujme základní pozici. Na povel psovoda si pes lehá. Psovod může dát povel k setrvání na místě a obejde ležícího psa zepředu. Po obejití se zastaví vedle ležícího psa a krátce v pozici setrvá. Během pohybu psovoda pes nesmí změnit svoji polohu ani pozici.',
    ],
    subParts: [
      { text: 'sedni', main: false },
      { text: 'lehni', main: true },
      { text: 'psovod stojí po každé pozici vedle psa', main: false },
      { text: 'psovod obchází psa, pes leží', main: true },
      { text: 'psovod stojí po obejití vedle psa', main: false },
    ],
    sequencing: {},
    image: 'z-005',
    sourcePage: 20,
  },
  {
    code: 'Z-006',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Obrat vpravo za chůze',
    description: ['Tým provede před kartou obrat vpravo o 90° a bez zastavení pokračuje dál.'],
    subParts: [{ text: 'obrat vpravo', main: true }],
    sequencing: {},
    image: 'z-006',
    sourcePage: 20,
  },
  {
    code: 'Z-007',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Obrat vlevo za chůze',
    description: ['Tým provede před kartou obrat vlevo o 90° a bez zastavení pokračuje dál.'],
    subParts: [{ text: 'obrat vlevo', main: true }],
    sequencing: {},
    image: 'z-007',
    sourcePage: 21,
  },
  {
    code: 'Z-008',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Obrat zpět vpravo',
    description: [
      'Tým provede před kartou obrat vpravo o 180° a bez zastavení pokračuje dál. Obrat v malém oblouku je dovolen.',
    ],
    subParts: [{ text: 'obrat vpravo 180°', main: true }],
    sequencing: {},
    image: 'z-008',
    sourcePage: 21,
  },
  {
    code: 'Z-009',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Obrat zpět vlevo',
    description: [
      'Tým provede před kartou obrat vlevo o 180° a bez zastavení pokračuje dál. Obrat v malém oblouku je dovolen.',
    ],
    subParts: [{ text: 'obrat vlevo 180°', main: true }],
    sequencing: {},
    image: 'z-009',
    sourcePage: 21,
  },
  {
    code: 'Z-010',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Čelem vzad - pes za psovodem',
    description: [
      'Psovod provede před kartou obrat do té strany, na které se nachází pes, zatímco pes provádí obrat na tu stranu, kde se nachází psovod. Pes obchází psovoda zezadu a vrací se na výchozí stranu u nohy psovoda. Tým poté bez zastavení pokračuje dál.',
    ],
    subParts: [{ text: 'čelem vzad - pes za psovodem', main: true }],
    sequencing: {},
    image: 'z-010',
    sourcePage: 21,
  },
  {
    code: 'Z-011',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: '270° vpravo',
    description: [
      'Tým provede před kartou obrat vpravo o 270°, přičemž psovod provádí obrat na místě. Lehké posuny nohou ve směru obratu jsou povoleny. Pes během provádění cviku zůstává stále u nohy.',
    ],
    subParts: [
      { text: '270° otočení vpravo', main: true },
      { text: 'pes zůstává u nohy psovoda', main: true },
    ],
    sequencing: {},
    image: 'z-011',
    sourcePage: 22,
  },
  {
    code: 'Z-012',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: '270° vlevo',
    description: [
      'Tým provede před kartou obrat vlevo o 270°, přičemž psovod provádí obrat na místě. Lehké posuny nohou ve směru obratu jsou povoleny. Pes během provádění cviku zůstává stále u nohy.',
    ],
    subParts: [
      { text: '270° otočení vlevo', main: true },
      { text: 'pes zůstává u nohy psovoda', main: true },
    ],
    sequencing: {},
    image: 'z-012',
    sourcePage: 22,
  },
  {
    code: 'Z-013',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: '360° vpravo',
    description: [
      'Tým provede v místě pro vykonání cviku obrat vpravo o 360°, přičemž psovod provádí obrat na místě. Lehké posuny nohou ve směru obratu jsou povoleny. Pes během provádění cviku zůstává stále u nohy. Z pohledu psovoda se nemění směr postupu.',
    ],
    subParts: [
      { text: '360° otočení vpravo', main: true },
      { text: 'pes zůstává u nohy psovoda', main: true },
    ],
    sequencing: {},
    image: 'z-013',
    sourcePage: 22,
  },
  {
    code: 'Z-014',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'AB',
    name: 'Předsednutí',
    description: [
      'K tomuto cviku je třeba přidat doplňkovou kartu D0a–d.',
      'V místě pro provedení cviku dává psovod psovi povel k předsednutí. Během pohybu psa (než si předsedne) může psovod udělat až čtyři kroky vzad v přímém směru, ale přitom nesmí korigovat úkrokem do strany pozici psa. Během předsednutí a během provádění cviku z doplňkové karty nesmí psovod pohybovat nohama.',
    ],
    subParts: [
      { text: 'předsednutí', main: true },
      { text: 'ukončení D0a–d', main: false },
    ],
    sequencing: {
      // p. 23: "K tomuto cviku je třeba přidat doplňkovou kartu D0a–d."
      requiresSupplementary: true,
    },
    image: 'z-014',
    sourcePage: 23,
  },
  {
    code: 'Z-015',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Pomalé tempo',
    description: [
      'V místě pro provedení cviku tým zpomalí své tempo. Změna tempa musí být u psovoda i psa zřetelná. Tým udržuje pomalé tempo, dokud jiný cvik toto tempo nezmění (statický cvik, změna tempa, cíl - tento cvik může být i na konci parkuru).',
    ],
    subParts: [
      { text: 'změna tempa psovod, pes', main: true },
      { text: 'udržení tempa až do ukončení cviku', main: true },
    ],
    sequencing: {
      // p. 23: pace change — holds until a static exercise, another pace or the finish.
      pace: 'slow',
    },
    image: 'z-015',
    sourcePage: 23,
  },
  {
    code: 'Z-016',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Rychlé tempo',
    description: [
      'V místě pro provedení cviku tým zrychlí své tempo. Změna tempa musí být u psovoda i psa zřetelná. Tým udržuje rychlé tempo, dokud jiný cvik toto tempo nezmění (statický cvik, změna tempa, cíl - tento cvik může být i na konci parkuru).',
    ],
    subParts: [
      { text: 'změna tempa psovod, pes', main: true },
      { text: 'udržení tempa až do ukončení cviku', main: true },
    ],
    sequencing: {
      // p. 23: pace change — holds until a static exercise, another pace or the finish.
      pace: 'fast',
      // p. 62: RO-V — "pouze jako poslední karta".
      lastOnly: ['RO-V'],
    },
    image: 'z-016',
    sourcePage: 23,
  },
  {
    code: 'Z-017',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Normální tempo (chůze)',
    description: [
      'V místě pro provedení cviku změní tým tempo do normální chůze. Změna tempa musí být u psovoda i psa zřetelná.',
    ],
    subParts: [{ text: 'změna tempa psovod, pes', main: true }],
    sequencing: {
      // p. 24: pace change — holds until a static exercise, another pace or the finish.
      pace: 'normal',
    },
    image: 'z-017',
    sourcePage: 24,
  },
  {
    code: 'Z-018',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Spirála doprava',
    description: [
      'Tři kužely jsou rozestavěny v řadě za sebou s rozestupem 1,5 m od sebe. Karta je umístěna před prvním kuželem, viditelná ze směru příchodu týmu. Tým míjí kartu i kužely po své pravé straně (ve směru hodinových ručiček, pes u nohy psovoda), obejde třetí kužel (nejvzdálenější) a vrací se k prvnímu kuželu, který též obejde. Následně obejde druhý kužel a vrací se znovu k prvnímu, který opět obejde. Na konec obejde jen první kužel dokola. Směr postupu ze spirály určuje poloha další karty.',
    ],
    subParts: [
      { text: 'spirála doprava', main: true },
      { text: 'obejití 3. kuželu', main: false },
      { text: 'obejití 2. kuželu', main: false },
      { text: 'obejití 1. kuželu', main: false },
    ],
    sequencing: {
      equipment: ['cones'],
    },
    image: 'z-018',
    diagram: 'z-018-diagram',
    sourcePage: 24,
  },
  {
    code: 'Z-019',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Spirála doleva',
    description: [
      'Tři kužely jsou rozestavěny v řadě za sebou s rozestupem 1,5 m od sebe. Karta je umístěna před prvním kuželem, viditelná ze směru příchodu týmu. Tým míjí kartu i kužely po své levé straně (proti směru hodinových ručiček, pes u nohy psovoda), obejde třetí kužel (nejvzdálenější) a vrací se k prvnímu kuželu, který též obejde. Následně obejde druhý kužel a vrací se znovu k prvnímu, který opět obejde. Na konec obejde jen první kužel dokola. Směr postupu ze spirály určuje poloha další karty.',
    ],
    subParts: [
      { text: 'spirála doleva', main: true },
      { text: 'obejití 3. kuželu', main: false },
      { text: 'obejití 2. kuželu', main: false },
      { text: 'obejití 1. kuželu', main: false },
    ],
    sequencing: {
      equipment: ['cones'],
    },
    image: 'z-019',
    diagram: 'z-019-diagram',
    sourcePage: 25,
  },
  {
    code: 'Z-020',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Slalom jednoduchý',
    description: [
      'Čtyři kužely jsou rozestavěny v řadě za sebou s rozestupem 1,5 m od sebe. Karta je umístěna před prvním kuželem, viditelná ze směru příchodu týmu. Tým vstupuje do slalomu vždy zprava (tj. první kužel po své levé straně). Směr postupu ze slalomu závisí na poloze další karty.',
    ],
    subParts: [
      { text: 'vstup správnou stranou do slalomu', main: false },
      { text: 'slalom jednoduchý', main: true },
    ],
    sequencing: {
      equipment: ['cones'],
    },
    image: 'z-020',
    sourcePage: 25,
  },
  {
    code: 'Z-021',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Slalom tam a zpět',
    description: [
      'Čtyři kužely jsou rozestavěny v řadě za sebou s rozestupem 1,5 m od sebe. Karta je umístěna před prvním kuželem, viditelná ze směru příchodu týmu. Tým vstupuje do slalomu vždy zprava (tj. první kužel po levé straně). A překoná jej ve směru tam i zpět. Směr postupu ze slalomu závisí na poloze další karty.',
    ],
    subParts: [
      { text: 'vstup správnou stranou do slalomu', main: false },
      { text: 'slalom tam a zpět', main: true },
    ],
    sequencing: {
      equipment: ['cones'],
    },
    image: 'z-021',
    sourcePage: 25,
  },
  {
    code: 'Z-022',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Figura 8 bez rušivého vlivu',
    description: [
      'Čtyři prázdné misky přikryté poklopem jsou rozestavěny na vrcholech imaginárního kosočtverce tak, že pomyslná delší spojnice dvou protilehlých misek je 3 m a kratší pomyslná spojnice druhých dvou protilehlých misek je 1,5 m od sebe. Vstup do figury určuje karta, kterou tým vždy míjí po své levé straně (karta vždy vlevo od psa). Při provádění figury tým musí celkem 3x protnout pomyslný střed obrazce, přičemž vždy postupně obchází misky ležící na delší pomyslné spojnici. Východ z figury se vždy nachází na protilehlé straně proti vstupu.',
    ],
    subParts: [
      { text: 'správné uvedení do cviku', main: false },
      { text: 'průchod 3 x středem', main: false },
      { text: 'míjení misky, aniž by byla převržena nebo pes chňapal po poklopu', main: true },
      {
        text: 'nebude-li hlavní cvik předveden, hodnocení je -10 bodů, bez možnosti opakování',
        main: false,
      },
    ],
    sequencing: {
      equipment: ['bowls'],
    },
    image: 'z-022',
    sourcePage: 26,
  },
  {
    code: 'Z-023',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop – pes okolo psovoda – stop',
    description: [
      'Tým zastaví u karty v místě pro vykonání cviku a zaujme základní pozici. Pes oběhne psovoda zepředu a poté opět usedá u nohy psovoda. Psovod zůstává stát po celou dobu cviku (tj. nehýbe nohama)',
    ],
    subParts: [
      { text: 'sed', main: false },
      { text: 'pes okolo psovoda', main: true },
      { text: 'sed', main: false },
    ],
    sequencing: {},
    image: 'z-023',
    sourcePage: 26,
  },
  {
    code: 'Z-024',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop – jeden krok vpřed - stop',
    description: [
      'Tým zastaví u karty v místě pro vykonání cviku a zaujme základní pozici. Na povel psovoda tým postoupí o jeden krok vpřed a zaujímá základní pozici.',
    ],
    subParts: [
      { text: 'sed', main: false },
      { text: '1 krok', main: false },
      { text: 'sed', main: false },
    ],
    sequencing: {},
    image: 'z-024',
    sourcePage: 26,
  },
  {
    code: 'Z-025',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'AB',
    name: 'Předsednutí jeden krok zpět',
    description: [
      'K tomuto cviku je třeba přidat doplňkovou kartu D0a–d.',
      'V místě pro provedení cviku dává psovod psovi povel k předsednutí. Během pohybu psa (než si předsedne) může psovod udělat až čtyři kroky vzad v přímém směru, ale přitom nesmí korigovat úkrokem do strany pozici psa. Poté co pes zaujme pozici před psovodem, udělá psovod jeden krok vzad, pes jej následuje a znovu usedá před psovodem. Během předsednutí a během provádění cviku z doplňkové karty nesmí psovod pohybovat nohama.',
    ],
    subParts: [
      { text: '2 x předsednutí', main: true },
      { text: 'následování kroku zpět', main: false },
      { text: 'ukončení D0a–d', main: false },
    ],
    sequencing: {
      // p. 27: "K tomuto cviku je třeba přidat doplňkovou kartu D0a–d."
      requiresSupplementary: true,
    },
    image: 'z-025',
    sourcePage: 27,
  },
  {
    code: 'Z-026',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Kruhová spirála – doprava',
    description: [
      'Tři kužely jsou rozestavěny v řadě za sebou s rozestupem 1,5 m od sebe. Karta je umístěna před prvním kuželem, viditelná ze směru příchodu týmu. Tým míjí kartu i kužely po své pravé straně (ve směru hodinových ručiček, pes u nohy psovoda). Tým obejde první kužel, pokračuje ke druhému, který též obejde, a jako poslední obejde třetí kužel v řadě. Směr postupu ze spirály určuje poloha další karty.',
    ],
    subParts: [
      { text: 'spirála - doprava', main: true },
      { text: 'obejití 1. kuželu', main: false },
      { text: 'obejití 2. kuželu', main: false },
      { text: 'obejití 3. kuželu', main: false },
    ],
    sequencing: {
      equipment: ['cones'],
    },
    image: 'z-026',
    sourcePage: 27,
  },
  {
    code: 'Z-027',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: 'Kruhová spirála – doleva',
    description: [
      'Tři kužely jsou rozestavěny v řadě za sebou s rozestupem 1,5 m od sebe. Karta je umístěna před prvním kuželem, viditelná ze směru příchodu týmu. Tým míjí kartu i kužely po své levé straně (proti směru hodinových ručiček, pes u nohy psovoda). Tým obejde první kužel, pokračuje ke druhému, který též obejde, a jako poslední obejde třetí kužel v řadě. Směr postupu ze spirály určuje poloha další karty.',
    ],
    subParts: [
      { text: 'spirála - doleva', main: true },
      { text: 'obejití 1. kuželu', main: false },
      { text: 'obejití 2. kuželu', main: false },
      { text: 'obejití 3. kuželu', main: false },
    ],
    sequencing: {
      equipment: ['cones'],
    },
    image: 'z-027',
    sourcePage: 28,
  },
  {
    code: 'Z-028',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: '225° vpravo',
    description: [
      'Tým provede před kartou obrat vpravo o 225°, přičemž psovod provádí obrat na místě. Lehké posuny nohou ve směru obratu jsou povoleny. Pes během provádění cviku zůstává stále u nohy.',
    ],
    subParts: [
      { text: '225° otočení vpravo', main: true },
      { text: 'pes zůstává u nohy psovoda', main: true },
    ],
    sequencing: {},
    image: 'z-028',
    sourcePage: 28,
  },
  {
    code: 'Z-029',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'B',
    name: '225° vlevo',
    description: [
      'Tým provede před kartou obrat vlevo o 225°, přičemž psovod provádí obrat na místě. Lehké posuny nohou ve směru obratu jsou povoleny. Pes během provádění cviku zůstává stále u nohy.',
    ],
    subParts: [
      { text: '225° otočení vlevo', main: true },
      { text: 'pes zůstává u nohy psovoda', main: true },
    ],
    sequencing: {},
    image: 'z-029',
    sourcePage: 28,
  },
  {
    code: 'Z-030',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop - vpravo - stop',
    description: [
      'Tým se zastaví před kartou a zaujme základní pozici. Poté psovod společně se psem během obratu vpravo provede 3 kroky, a následně tým opět zaujme základní pozici.',
    ],
    subParts: [
      { text: 'základní pozice', main: false },
      { text: '3 kroky nohou', main: false },
      { text: 'základní pozice', main: false },
      { text: 'obrat vpravo', main: true },
    ],
    sequencing: {},
    image: 'z-030',
    sourcePage: 29,
  },
  {
    code: 'Z-031',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'A',
    name: 'Stop - vlevo - stop',
    description: [
      'Tým se zastaví před kartou a zaujme základní pozici. Poté psovod společně se psem během obratu vlevo provede 3 kroky, a následně tým opět zaujme základní pozici.',
    ],
    subParts: [
      { text: 'základní pozice', main: false },
      { text: '3 kroky nohou', main: false },
      { text: 'základní pozice', main: false },
      { text: 'obrat vlevo', main: true },
    ],
    sequencing: {},
    image: 'z-031',
    sourcePage: 29,
  },
  {
    code: 'Z-032',
    ruleset: 'CZ',
    kind: 'exercise',
    exerciseType: 'AB',
    name: 'Předsednutí - 1 krok vzad - lehni',
    description: [
      'K tomuto cviku je třeba přidat doplňkovou kartu D0a–d.',
      'V místě pro provedení cviku dává psovod psovi povel k předsednutí. Během pohybu psa (než si předsedne) může psovod udělat až čtyři kroky vzad v přímém směru, ale přitom nesmí korigovat úkrokem do strany pozici psa. Poté co pes zaujme pozici před psovodem, udělá psovod jeden krok vzad, pes jej následuje a poté ulehá před psovodem. Během předsednutí, ulehnutí a během provádění cviku z doplňkové karty nesmí psovod pohybovat nohama.',
    ],
    subParts: [
      { text: 'Předsednutí', main: false },
      { text: 'Následování kroku zpět', main: false },
      { text: 'Leh před psovodem', main: false },
      { text: 'Ukončení D0a-d', main: false },
    ],
    sequencing: {
      // p. 29: "K tomuto cviku je třeba přidat doplňkovou kartu D0a–d."
      requiresSupplementary: true,
    },
    image: 'z-032',
    sourcePage: 29,
  },
]
